#%RAML 1.0
title: Customer API
version: v1
baseUri: http://proj-customer/api
mediaType:
  - application/json

types:
  Customer:
    type: object
    properties:
      id: number
      nome: string
  Account:
    type: object
    properties:
      agencia: string
      conta: string

/customers:
  get:
    responses:
      200:
        body: Customer[]
  post:
    body: Customer
    responses:
      201:
  /{customer_id}:
    get:
      responses:
        200:
          body: Customer
        400:
    put:
      body: Customer
      responses:
        201:
        204:
    delete:
      responses:
        204:
    /accounts:
      get:
        responses:
          200:
            body: Account[]
