#%RAML 1.0 Library

types:
  Customer:
    displayName: Customer Type
    description: Cliente do banco
    type: object
    properties:
      id:
        displayName: ID Cliente
        type: number
      nome:
        displayName: Nome do Cliente
        type: string

  Account:
    displayName: Account Type
    description: Conta bancária
    type: object
    properties:
      agencia:
        displayName: Agência
        type: string
      conta:
        displayName: Conta Corrente
        type: string
        pattern: ˆ[0-9][5]$
