#%RAML 1.0
title: New API
version: v1
baseUri: http://api.samplehost.com

/users:
  /authors:
    /{authorname}:
  /books:
    get:
      queryParameters:
          author:
            displayName: Author
            type: string
            description: Author's name
            example: Fabricio
            required: false
          publicationYear:
          rating:
          isbn:
      responses:

    put:
    post:
