#%RAML 1.0
title: Customer API
version: v1
baseUri: http://proj-customer/api
mediaType:
  - application/json

/customers:
  get:
  post:
  /{customer_id}:
    get:
    put:
    delete:
    /accounts:
      get:
